apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: codequarkusio-sozu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codequarkusio-sozu
    app.kubernetes.io/part-of: my-app
  name: codequarkusio-sozu
  namespace: manderse-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: codequarkusio-sozu
    weight: null
status: {}
