apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: codequarkusio-sozu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codequarkusio-sozu
    app.kubernetes.io/part-of: my-app
  name: codequarkusio-sozu
  namespace: manderse-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: codequarkusio-sozu
status:
  loadBalancer: {}
